### ISSUE TITLE
整个硬件实现的输入是什么？What is the input?

### ISSUE THREAD

**Issue by xenonz95** [cea-wind/hls_ldpc_dec#1]
我最近因为项目需要才开始学ldpc，大概了解到你的这个实现是在解一个全长1536，实际数据1024bit的码，但是十分不明白为什么输入是1536个字节，而输出是1024bit，这样输入不是大了8倍么？这么看来输入应该不是编码后的数据，那么你这个模块实际的输入是什么呢？

**Comment by cea-wind** [comment]
这里实现的是ldpc的软判决算法（归一化最小和算法)，输入的是8bit量化的软信息，而不是0/1。可以根据实际的信道计算软信息，然后将其量化为8bit即可。

**Comment by xenonz95** [comment]
非常感谢您的快速回复，不过我对各种术语也不太明白，您的意思是这8位相当于是把信息从0到1划分为256份，然后这个模块的输出是用类似最大似然的方式估计出来的数据么？
如果我想仅仅只是先实现功能，输入1536bit，输出1024bit，把你的测试数据中正数作为1负数作为0就行么？
然后这样用肯定性能很糟糕，浪费了八倍的输入，如果要做一个适合于1536bit的解码器，我是应该了解一些硬判决算法重新实现，还是您的这份代码其实也可以简单修改为硬输入的呢？
十分感谢

**Comment by cea-wind** [comment]
你的理解是对的。直接采用正负1作为输入也是可行的，但是不是最优的。具体采用什么算法，需要结合具体的应用，建议先了解一些基本的算法，结合应用场景选择合适的进行实现。
