### ISSUE TITLE
insights about LDPC routing

### ISSUE THREAD

**Issue by maomran** [cea-wind/hls_ldpc_dec#2]
This implementation seem to be for WIFI standard, I would like to extend it to support DVB-S2 standard. Can you explain the rowPara and pidx matrices? they seem to be indices for routing between CNs and VNs, however I still can't fully map it to the base H-matrix.
Also, if I am not mistaken each colUpdate function takes pointer arguments to arrays of [512], isn't is supposed to be 64?

**Comment by cea-wind** [comment]
In this example , using a 64 length array is enough.

I sperate H-matrix into 80 cyclic matrix, those matrix are numbered by column direction. So, when row update process, I selecting the correct cyclic matrix through rowPara.  The reason for using pidx is the same as for rowparam, pidx is the id inside cyclic matrix.
you can generate rowPara with the following code, where m is the mother [mother matrix](https://github.com/cea-wind/hls_ldpc_dec/blob/master/matlabcode/MotherMatrix_2_3_A.txt)
```
A = -ones(8,24);
cnt = 0;
for i = 1:24
	for j = 1:8
		if(m(j,i)~=-1)
			A(j,i) = cnt;
			cnt++;
		end
	end
end
rowPara = zeros(1,80);
cnt = 1
for i = 1:8
	for j = 1:24
		if(A(i,j)~=-1)
			rowPara(cnt) = A(i,j);
			cnt++;
		end
	end
end
```

**Comment by maomran** [comment]
Yea I tried to map it to the matlab code, and figured that rowPara is the row_idx and col_idx is mapped to sel[25] idnex array. 
There is pidx that I guess is mapped to row_offset but I couldn't find them matching. 
Also, it would be nice if you give some insights about the difference between each colupdate{2,3,6} functions?

**Comment by cea-wind** [comment]
In this example，pidx can generate through mother matrix directly. Skip -1 in mother matrix, you can get the pidx.

The column weight  of this ldpc code is different. (including 2/3/6) So, I use diffenent function to update Mutual information.
